version: '3.8'

services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: reefz-portfolio
    ports:
      - "4444:4173"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    # Add resource limits for efficiency
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4173/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
